//! Windows WebAuthn PRF adapter for a cross-platform FIDO2 authenticator.
//!
//! These synchronous calls belong on a worker thread. Registration changes
//! persistent authenticator state and must be invoked only after explicit UI
//! consent. This module neither stores credentials nor chooses a recovery path.

use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use windows::Win32::Foundation::HWND;
use windows::Win32::Networking::WindowsWebServices::*;
use windows_core::{w, BOOL, GUID, HRESULT, PCWSTR};
use zeroize::{Zeroize, Zeroizing};

const RP_ID: PCWSTR = w!("sakura-input.local");
const RP_NAME: PCWSTR = w!("Sakura Input Pad");
const USER_NAME: PCWSTR = w!("Sakura Input Pad user");
const CLIENT_ORIGIN: &str = "https://sakura-input.local";
const MIN_PRF_API_VERSION: u32 = 7;
const AUTH_DATA_MIN_LEN: usize = 37;
const UV_FLAG: u8 = 0x04;
const MAX_CREDENTIAL_ID: usize = 1024;

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum WebAuthnError {
    Unsupported,
    InvalidInput,
    Busy,
    EntropyUnavailable,
    CancelledOrTimedOut,
    CredentialMismatch,
    UserVerificationMissing,
    PrfUnavailable,
    MalformedResponse,
    Windows(HRESULT),
}

/// Opaque credential handle to save with the memo's protected metadata.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RegisteredCredential {
    pub id: Vec<u8>,
}

/// A unique cancellation ID may be shared with UI code while one operation is
/// pending. Cancellation is best effort; the OS operation also has a timeout.
#[derive(Debug)]
pub struct Cancellation {
    id: GUID,
    requested: AtomicBool,
}

impl Cancellation {
    pub fn new() -> Result<Self, WebAuthnError> {
        check_capability()?;
        // SAFETY: no pointers; the OS initializes the returned GUID.
        let id = unsafe { WebAuthNGetCancellationId() }.map_err(map_error)?;
        Ok(Self {
            id,
            requested: AtomicBool::new(false),
        })
    }

    pub fn cancel(&self) -> Result<(), WebAuthnError> {
        self.requested.store(true, Ordering::Release);
        // SAFETY: `id` remains alive for the duration of the call.
        unsafe { WebAuthNCancelCurrentOperation(&self.id) }.map_err(map_error)
    }

    pub fn is_cancelled(&self) -> bool {
        self.requested.load(Ordering::Acquire)
    }
}

/// Checks OS API support, not whether the inserted key supports PRF.
pub fn check_capability() -> Result<(), WebAuthnError> {
    // SAFETY: this function has no inputs or owned output.
    let version = unsafe { WebAuthNGetApiVersionNumber() };
    if version < MIN_PRF_API_VERSION {
        Err(WebAuthnError::Unsupported)
    } else {
        Ok(())
    }
}

/// Creates one non-resident credential with PRF enabled. `challenge` must be
/// freshly generated by the caller for this operation. The returned ID is not
/// a secret, but must be bound to this RP when persisted by the caller.
pub fn register(
    parent: HWND,
    user_id: &[u8; 32],
    challenge: &[u8; 32],
    timeout: Duration,
    cancellation: &Cancellation,
) -> Result<RegisteredCredential, WebAuthnError> {
    check_capability()?;
    let timeout_ms = timeout_ms(timeout)?;
    let mut user_id = *user_id;
    let mut client_json = client_data("webauthn.create", challenge);
    let rp = WEBAUTHN_RP_ENTITY_INFORMATION {
        dwVersion: WEBAUTHN_RP_ENTITY_INFORMATION_CURRENT_VERSION,
        pwszId: RP_ID,
        pwszName: RP_NAME,
        ..Default::default()
    };
    let user = WEBAUTHN_USER_ENTITY_INFORMATION {
        dwVersion: WEBAUTHN_USER_ENTITY_INFORMATION_CURRENT_VERSION,
        cbId: user_id.len() as u32,
        pbId: user_id.as_mut_ptr(),
        pwszName: USER_NAME,
        pwszDisplayName: USER_NAME,
        ..Default::default()
    };
    let mut cose = WEBAUTHN_COSE_CREDENTIAL_PARAMETER {
        dwVersion: WEBAUTHN_COSE_CREDENTIAL_PARAMETER_CURRENT_VERSION,
        pwszCredentialType: WEBAUTHN_CREDENTIAL_TYPE_PUBLIC_KEY,
        lAlg: WEBAUTHN_COSE_ALGORITHM_ECDSA_P256_WITH_SHA256,
    };
    let params = WEBAUTHN_COSE_CREDENTIAL_PARAMETERS {
        cCredentialParameters: 1,
        pCredentialParameters: &mut cose,
    };
    let client = client_data_view(&mut client_json);
    let mut cancellation_id = cancellation.id;
    // Older YubiKey 5 firmware supports CTAP hmac-secret even when it does
    // not advertise WebAuthn PRF. Ask Windows to enable that extension on the
    // new credential as well; GetAssertion uses the same scoped PRF salts.
    let mut legacy_hmac_secret = BOOL(1);
    let mut legacy_extension = WEBAUTHN_EXTENSION {
        pwszExtensionIdentifier: WEBAUTHN_EXTENSIONS_IDENTIFIER_HMAC_SECRET,
        cbExtension: std::mem::size_of::<BOOL>() as u32,
        pvExtension: (&mut legacy_hmac_secret as *mut BOOL).cast(),
    };
    let options = WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS {
        dwVersion: WEBAUTHN_AUTHENTICATOR_MAKE_CREDENTIAL_OPTIONS_VERSION_7,
        dwTimeoutMilliseconds: timeout_ms,
        Extensions: WEBAUTHN_EXTENSIONS {
            cExtensions: 1,
            pExtensions: &mut legacy_extension,
        },
        dwAuthenticatorAttachment: WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM,
        dwUserVerificationRequirement: WEBAUTHN_USER_VERIFICATION_REQUIREMENT_REQUIRED,
        dwAttestationConveyancePreference: WEBAUTHN_ATTESTATION_CONVEYANCE_PREFERENCE_NONE,
        bEnablePrf: true.into(),
        pCancellationId: &mut cancellation_id,
        ..Default::default()
    };
    // SAFETY: all referenced inputs live through the synchronous OS call.
    let raw = unsafe {
        WebAuthNAuthenticatorMakeCredential(parent, &rp, &user, &params, &client, Some(&options))
    }
    .map_err(map_error)?;
    if raw.is_null() {
        return Err(WebAuthnError::MalformedResponse);
    }
    let attestation = Attestation(raw);
    // SAFETY: successful API call returns an owned, non-null attestation until
    // its RAII guard frees it. Validation bounds all pointer-backed reads.
    let attestation = unsafe { &*attestation.0 };
    if attestation.dwVersion < WEBAUTHN_CREDENTIAL_ATTESTATION_VERSION_5 {
        return Err(WebAuthnError::Unsupported);
    }
    require_external_transport(attestation.dwUsedTransport)?;
    if !attestation.bPrfEnabled.as_bool() && !legacy_hmac_secret_enabled(&attestation.Extensions)? {
        return Err(WebAuthnError::PrfUnavailable);
    }
    // SAFETY: the attestation guard owns this Windows buffer through validation.
    let auth_data = unsafe {
        bytes(
            attestation.pbAuthenticatorData,
            attestation.cbAuthenticatorData,
        )
    }?;
    require_uv(auth_data)?;
    // SAFETY: the attestation guard owns the credential ID until it is copied.
    let id = unsafe { bytes(attestation.pbCredentialId, attestation.cbCredentialId) }?;
    validate_credential_id(id)?;
    Ok(RegisteredCredential { id: id.to_vec() })
}

/// Derives a 32-byte PRF result from the saved credential and caller's salt.
/// `challenge` must be fresh. The returned buffer is zeroized on drop.
pub fn assert_prf(
    parent: HWND,
    credential_id: &[u8],
    salt: &[u8; 32],
    challenge: &[u8; 32],
    timeout: Duration,
    cancellation: &Cancellation,
) -> Result<Zeroizing<[u8; 32]>, WebAuthnError> {
    check_capability()?;
    validate_credential_id(credential_id)?;
    let timeout_ms = timeout_ms(timeout)?;
    let mut client_json = client_data("webauthn.get", challenge);
    let client = client_data_view(&mut client_json);
    let mut credential = WEBAUTHN_CREDENTIAL {
        dwVersion: WEBAUTHN_CREDENTIAL_CURRENT_VERSION,
        cbId: credential_id.len() as u32,
        pbId: credential_id.as_ptr().cast_mut(),
        pwszCredentialType: WEBAUTHN_CREDENTIAL_TYPE_PUBLIC_KEY,
    };
    let mut hmac_salt = WEBAUTHN_HMAC_SECRET_SALT {
        cbFirst: 32,
        pbFirst: salt.as_ptr().cast_mut(),
        ..Default::default()
    };
    let mut hmac_salts = WEBAUTHN_HMAC_SECRET_SALT_VALUES {
        pGlobalHmacSalt: &mut hmac_salt,
        ..Default::default()
    };
    let mut cancellation_id = cancellation.id;
    let options = WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS {
        dwVersion: WEBAUTHN_AUTHENTICATOR_GET_ASSERTION_OPTIONS_VERSION_7,
        dwTimeoutMilliseconds: timeout_ms,
        CredentialList: WEBAUTHN_CREDENTIALS {
            cCredentials: 1,
            pCredentials: &mut credential,
        },
        dwAuthenticatorAttachment: WEBAUTHN_AUTHENTICATOR_ATTACHMENT_CROSS_PLATFORM,
        dwUserVerificationRequirement: WEBAUTHN_USER_VERIFICATION_REQUIREMENT_REQUIRED,
        pCancellationId: &mut cancellation_id,
        pHmacSecretSaltValues: &mut hmac_salts,
        ..Default::default()
    };
    // SAFETY: all referenced inputs live through the synchronous OS call.
    let raw = unsafe { WebAuthNAuthenticatorGetAssertion(parent, RP_ID, &client, Some(&options)) }
        .map_err(map_error)?;
    if raw.is_null() {
        return Err(WebAuthnError::MalformedResponse);
    }
    let assertion = Assertion(raw);
    // SAFETY: successful API call returns owned output until the guard frees it.
    let assertion = unsafe { &*assertion.0 };
    if assertion.dwVersion < WEBAUTHN_ASSERTION_VERSION_4 {
        return Err(WebAuthnError::Unsupported);
    }
    require_external_transport(assertion.dwUsedTransport)?;
    // SAFETY: the assertion guard owns the returned ID during comparison.
    let returned_id = unsafe { bytes(assertion.Credential.pbId, assertion.Credential.cbId) }?;
    if returned_id != credential_id {
        return Err(WebAuthnError::CredentialMismatch);
    }
    // SAFETY: the assertion guard owns the authenticator data during validation.
    let auth_data = unsafe { bytes(assertion.pbAuthenticatorData, assertion.cbAuthenticatorData) }?;
    require_uv(auth_data)?;
    if assertion.pHmacSecret.is_null() {
        return Err(WebAuthnError::PrfUnavailable);
    }
    // SAFETY: pHmacSecret is an OS-owned field present until the assertion is freed.
    let output = unsafe { &*assertion.pHmacSecret };
    // SAFETY: the assertion guard owns this nested PRF output until it is copied.
    let first = unsafe { bytes(output.pbFirst, output.cbFirst) }?;
    validate_prf_length(first)?;
    let mut result = Zeroizing::new([0_u8; 32]);
    result.copy_from_slice(first);
    Ok(result)
}

struct Attestation(*mut WEBAUTHN_CREDENTIAL_ATTESTATION);
impl Drop for Attestation {
    fn drop(&mut self) {
        // SAFETY: the OS owns this pointer, returned by MakeCredential once.
        unsafe { WebAuthNFreeCredentialAttestation(Some(self.0)) };
    }
}

struct Assertion(*mut WEBAUTHN_ASSERTION);
impl Drop for Assertion {
    fn drop(&mut self) {
        // The PRF result is returned in OS-owned writable memory. Scrub its
        // bounded outputs before releasing the assertion allocation.
        // SAFETY: this guard owns a non-null Windows assertion until free.
        let assertion = unsafe { &mut *self.0 };
        if assertion.dwVersion >= WEBAUTHN_ASSERTION_VERSION_3 && !assertion.pHmacSecret.is_null() {
            // SAFETY: the PRF output is nested in this live OS-owned object.
            let salt = unsafe { &mut *assertion.pHmacSecret };
            for (ptr, len) in [(salt.pbFirst, salt.cbFirst), (salt.pbSecond, salt.cbSecond)] {
                if !ptr.is_null() && len <= 64 {
                    // SAFETY: the OS reports the size of its mutable byte buffer.
                    unsafe { std::slice::from_raw_parts_mut(ptr, len as usize) }.zeroize();
                }
            }
        }
        // SAFETY: the OS owns this pointer, returned by GetAssertion once.
        unsafe { WebAuthNFreeAssertion(self.0) };
    }
}

fn timeout_ms(timeout: Duration) -> Result<u32, WebAuthnError> {
    let millis = timeout.as_millis();
    if !(1..=120_000).contains(&millis) {
        return Err(WebAuthnError::InvalidInput);
    }
    Ok(millis as u32)
}

fn validate_credential_id(id: &[u8]) -> Result<(), WebAuthnError> {
    if id.is_empty() || id.len() > MAX_CREDENTIAL_ID {
        Err(WebAuthnError::MalformedResponse)
    } else {
        Ok(())
    }
}

fn require_uv(auth_data: &[u8]) -> Result<(), WebAuthnError> {
    if auth_data.len() < AUTH_DATA_MIN_LEN {
        return Err(WebAuthnError::MalformedResponse);
    }
    if auth_data[32] & UV_FLAG == 0 {
        return Err(WebAuthnError::UserVerificationMissing);
    }
    Ok(())
}

fn validate_prf_length(first: &[u8]) -> Result<(), WebAuthnError> {
    if first.len() != 32 {
        Err(WebAuthnError::PrfUnavailable)
    } else {
        Ok(())
    }
}

fn legacy_hmac_secret_enabled(extensions: &WEBAUTHN_EXTENSIONS) -> Result<bool, WebAuthnError> {
    if extensions.cExtensions == 0 {
        return Ok(false);
    }
    if extensions.cExtensions > 16 || extensions.pExtensions.is_null() {
        return Err(WebAuthnError::MalformedResponse);
    }
    // SAFETY: Windows owns the attestation and its bounded extension array
    // until the caller's RAII guard frees it.
    let items = unsafe {
        std::slice::from_raw_parts(extensions.pExtensions, extensions.cExtensions as usize)
    };
    for item in items {
        // SAFETY: Windows owns this NUL-terminated extension identifier.
        let name = unsafe { item.pwszExtensionIdentifier.to_string() }
            .map_err(|_| WebAuthnError::MalformedResponse)?;
        if name == "hmac-secret" {
            if item.cbExtension != std::mem::size_of::<BOOL>() as u32 || item.pvExtension.is_null()
            {
                return Err(WebAuthnError::MalformedResponse);
            }
            // SAFETY: a matching Windows extension reports a BOOL-sized live
            // output; unaligned read avoids trusting its alignment.
            let enabled = unsafe { (item.pvExtension as *const BOOL).read_unaligned() };
            return Ok(enabled.as_bool());
        }
    }
    Ok(false)
}

fn require_external_transport(transport: u32) -> Result<(), WebAuthnError> {
    if transport
        & (WEBAUTHN_CTAP_TRANSPORT_USB | WEBAUTHN_CTAP_TRANSPORT_NFC | WEBAUTHN_CTAP_TRANSPORT_BLE)
        == 0
    {
        Err(WebAuthnError::Unsupported)
    } else {
        Ok(())
    }
}

unsafe fn bytes<'a>(ptr: *const u8, len: u32) -> Result<&'a [u8], WebAuthnError> {
    if ptr.is_null() || len > 1_048_576 {
        return Err(WebAuthnError::MalformedResponse);
    }
    // SAFETY: pointer and length are supplied by Windows and remain owned by
    // the surrounding output guard. The size cap prevents unbounded copies.
    Ok(unsafe { std::slice::from_raw_parts(ptr, len as usize) })
}

fn client_data_view(json: &mut Vec<u8>) -> WEBAUTHN_CLIENT_DATA {
    WEBAUTHN_CLIENT_DATA {
        dwVersion: WEBAUTHN_CLIENT_DATA_CURRENT_VERSION,
        cbClientDataJSON: json.len() as u32,
        pbClientDataJSON: json.as_mut_ptr(),
        pwszHashAlgId: WEBAUTHN_HASH_ALGORITHM_SHA_256,
    }
}

fn client_data(kind: &str, challenge: &[u8; 32]) -> Vec<u8> {
    format!(
        "{{\"type\":\"{kind}\",\"challenge\":\"{}\",\"origin\":\"{CLIENT_ORIGIN}\"}}",
        base64url(challenge)
    )
    .into_bytes()
}

fn base64url(input: &[u8]) -> String {
    const ALPHABET: &[u8; 64] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_";
    let mut out = String::with_capacity((input.len() * 4).div_ceil(3));
    for chunk in input.chunks(3) {
        let value = ((chunk[0] as u32) << 16)
            | ((chunk.get(1).copied().unwrap_or(0) as u32) << 8)
            | (chunk.get(2).copied().unwrap_or(0) as u32);
        out.push(ALPHABET[((value >> 18) & 63) as usize] as char);
        out.push(ALPHABET[((value >> 12) & 63) as usize] as char);
        if chunk.len() > 1 {
            out.push(ALPHABET[((value >> 6) & 63) as usize] as char);
        }
        if chunk.len() > 2 {
            out.push(ALPHABET[(value & 63) as usize] as char);
        }
    }
    out
}

fn map_error(error: windows_core::Error) -> WebAuthnError {
    let code = error.code();
    // NTE_USER_CANCELLED, HRESULT_FROM_WIN32(ERROR_CANCELLED), ERROR_TIMEOUT.
    if code.0 == 0x8009_0036_u32 as i32
        || code.0 == 0x8007_04c7_u32 as i32
        || code.0 == 0x8007_05b4_u32 as i32
    {
        WebAuthnError::CancelledOrTimedOut
    } else if code.0 == 0x8009_0029_u32 as i32 {
        WebAuthnError::Unsupported
    } else {
        // SAFETY: WebAuthNGetErrorName returns a NUL-terminated OS-owned name.
        let name = unsafe { WebAuthNGetErrorName(code).to_string() };
        match name.as_deref() {
            Ok("NotAllowedError") => WebAuthnError::CancelledOrTimedOut,
            Ok("NotSupportedError") => WebAuthnError::Unsupported,
            _ => WebAuthnError::Windows(code),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn os_capability_probe_does_not_touch_authenticator() {
        // This reads only the installed Windows WebAuthn API version.
        // SAFETY: this capability probe has no inputs or owned output.
        let version = unsafe { WebAuthNGetApiVersionNumber() };
        assert_eq!(check_capability().is_ok(), version >= MIN_PRF_API_VERSION);
    }

    #[test]
    fn user_verification_requires_full_authenticator_data_and_uv_bit() {
        assert_eq!(require_uv(&[0; 36]), Err(WebAuthnError::MalformedResponse));
        let mut data = [0_u8; 37];
        data[32] = 0x01;
        assert_eq!(
            require_uv(&data),
            Err(WebAuthnError::UserVerificationMissing)
        );
        data[32] |= UV_FLAG;
        assert_eq!(require_uv(&data), Ok(()));
    }

    #[test]
    fn prf_and_credential_lengths_are_strict() {
        assert_eq!(
            validate_prf_length(&[0; 31]),
            Err(WebAuthnError::PrfUnavailable)
        );
        assert_eq!(validate_prf_length(&[0; 32]), Ok(()));
        assert_eq!(
            validate_credential_id(&[]),
            Err(WebAuthnError::MalformedResponse)
        );
        assert_eq!(validate_credential_id(&[1]), Ok(()));
    }

    #[test]
    fn legacy_hmac_secret_attestation_requires_explicit_true_output() {
        let mut enabled = BOOL(1);
        let mut item = WEBAUTHN_EXTENSION {
            pwszExtensionIdentifier: WEBAUTHN_EXTENSIONS_IDENTIFIER_HMAC_SECRET,
            cbExtension: std::mem::size_of::<BOOL>() as u32,
            pvExtension: (&mut enabled as *mut BOOL).cast(),
        };
        let extensions = WEBAUTHN_EXTENSIONS {
            cExtensions: 1,
            pExtensions: &mut item,
        };
        assert_eq!(legacy_hmac_secret_enabled(&extensions), Ok(true));
        enabled = BOOL(0);
        assert_eq!(legacy_hmac_secret_enabled(&extensions), Ok(false));
        assert!(!enabled.as_bool());
        let mut malformed_item = WEBAUTHN_EXTENSION {
            cbExtension: 1,
            ..item
        };
        let malformed = WEBAUTHN_EXTENSIONS {
            cExtensions: 1,
            pExtensions: &mut malformed_item,
        };
        assert_eq!(
            legacy_hmac_secret_enabled(&malformed),
            Err(WebAuthnError::MalformedResponse)
        );
    }

    #[test]
    fn internal_or_missing_transport_is_rejected() {
        assert_eq!(
            require_external_transport(0),
            Err(WebAuthnError::Unsupported)
        );
        assert_eq!(
            require_external_transport(WEBAUTHN_CTAP_TRANSPORT_INTERNAL),
            Err(WebAuthnError::Unsupported)
        );
        assert_eq!(
            require_external_transport(WEBAUTHN_CTAP_TRANSPORT_USB),
            Ok(())
        );
    }

    #[test]
    fn challenge_is_base64url_without_padding() {
        let json = String::from_utf8(client_data("webauthn.get", &[0xff; 32])).unwrap();
        assert!(json.contains("__________________________________________8"));
        assert!(!json.contains('='));
    }

    #[test]
    fn timeout_is_bounded() {
        assert_eq!(timeout_ms(Duration::ZERO), Err(WebAuthnError::InvalidInput));
        assert_eq!(timeout_ms(Duration::from_secs(120)), Ok(120_000));
        assert_eq!(
            timeout_ms(Duration::from_secs(121)),
            Err(WebAuthnError::InvalidInput)
        );
    }

    #[test]
    fn cancellation_remains_requested_between_native_operations() {
        let Ok(cancellation) = Cancellation::new() else {
            return; // The capability probe is checked separately.
        };
        assert!(!cancellation.is_cancelled());
        // There is no active operation; the OS may reject that part. The
        // local flag still prevents the next registration/assertion edge.
        let _ = cancellation.cancel();
        assert!(cancellation.is_cancelled());
    }
}
