param(
    [string]$OutputDirectory = "",
    [string]$WorkDirectory = "",
    [string]$PreExportedModelDirectory = "",
    [switch]$ValidateOnly,
    [Alias('?')]
    [switch]$Help
)

$ErrorActionPreference = 'Stop'
$ProgressPreference = 'SilentlyContinue'

if ($Help) {
    Write-Output 'Usage: build-neural-reranker.ps1 [-OutputDirectory <path>] [-WorkDirectory <path>] [-PreExportedModelDirectory <path>] [-ValidateOnly]'
    Write-Output '  -ValidateOnly verifies an existing neural payload without downloading or building.'
    return
}

$repository = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..'))
if ([string]::IsNullOrWhiteSpace($OutputDirectory)) {
    $OutputDirectory = Join-Path $repository 'artifacts\release'
}
if ([string]::IsNullOrWhiteSpace($WorkDirectory)) {
    $WorkDirectory = Join-Path $env:USERPROFILE 'tmp\sakura-input-neural-build'
}
$OutputDirectory = [IO.Path]::GetFullPath($OutputDirectory)
$WorkDirectory = [IO.Path]::GetFullPath($WorkDirectory)

$modelId = 'ku-nlp/deberta-v2-tiny-japanese-char-wwm'
$modelRevision = '41bcb8a393383a039c7ee18ded6893ca82e668b7'
$ortVersion = '1.28.0'
$ortArchiveHash = 'abef733dacbe2f571547a7150b479b5cb9cc0df22f96c24983a42cadb1b4f8bc'
$ortArchiveUrl = "https://github.com/microsoft/onnxruntime/releases/download/v$ortVersion/onnxruntime-win-x64-$ortVersion.zip"
$modelDirectoryName = 'deberta-v2-tiny-japanese-char-wwm'
$manifestRelativePath = "neural/$modelDirectoryName/manifest.json"
$workerPackage = 'sakura-neural-worker'
$workerRelativePath = 'target/x86_64-pc-windows-msvc/release/sakura_neural_worker.exe'
$runtimeDllName = 'onnxruntime.dll'
$neuralPayloadFiles = @(
    'sakura_neural_worker.exe',
    $runtimeDllName,
    'neural/deberta-v2-tiny-japanese-char-wwm/model.onnx',
    'neural/deberta-v2-tiny-japanese-char-wwm/vocab.txt',
    'neural/deberta-v2-tiny-japanese-char-wwm/manifest.json',
    'licenses/onnxruntime-MIT.txt',
    'licenses/onnxruntime-ThirdPartyNotices.txt',
    'licenses/ku-nlp-deberta-v2-tiny-japanese-char-wwm.txt'
)

function Get-Sha256([string]$Path) {
    $stream = [IO.File]::OpenRead($Path)
    try {
        $sha = [Security.Cryptography.SHA256]::Create()
        try {
            return ([BitConverter]::ToString($sha.ComputeHash($stream))).Replace('-', '').ToLowerInvariant()
        } finally {
            $sha.Dispose()
        }
    } finally {
        $stream.Dispose()
    }
}

function Require-File([string]$Path, [string]$Description) {
    $item = [IO.FileInfo]::new($Path)
    if (-not $item.Exists -or $item.Length -le 0) {
        throw "$Description is missing or empty: $Path"
    }
    return $item
}

function Get-InstallerManifestText([object[]]$Records) {
    $lines = [Collections.Generic.List[string]]::new()
    $lines.Add('; Generated by scripts/build-neural-reranker.ps1. Do not edit.')
    $lines.Add('#define NeuralPayloadCount ' + $Records.Count)
    for ($index = 0; $index -lt $Records.Count; $index++) {
        $record = $Records[$index]
        $lines.Add("#define NeuralPayload$($index)Path `"$($record.path)`"")
        $lines.Add("#define NeuralPayload$($index)Bytes $($record.bytes)")
        $lines.Add("#define NeuralPayload$($index)Sha256 `"$($record.sha256)`"")
    }
    $lines.Add("#define NeuralModelId `"$modelId`"")
    $lines.Add("#define NeuralModelRevision `"$modelRevision`"")
    $lines.Add("#define NeuralOnnxRuntimeVersion `"$ortVersion`"")
    $lines.Add("#define NeuralOnnxRuntimeArchiveSha256 `"$ortArchiveHash`"")
    $lines.Add("#define NeuralWorkerPackage `"$workerPackage`"")
    return (($lines -join [Environment]::NewLine) + [Environment]::NewLine)
}

function Test-NeuralPayload([string]$PayloadDirectory) {
    if (-not [IO.Directory]::Exists($PayloadDirectory)) {
        throw "neural payload directory is missing: $PayloadDirectory"
    }

    $manifestPath = Join-Path $PayloadDirectory $manifestRelativePath.Replace('/', '\')
    Require-File $manifestPath 'neural reranker manifest' | Out-Null
    try {
        $manifest = [IO.File]::ReadAllText($manifestPath, [Text.UTF8Encoding]::new($false)) | ConvertFrom-Json
    } catch {
        throw "neural reranker manifest is not valid JSON: $manifestPath ($($_.Exception.Message))"
    }

    if ($manifest.schema_version -ne 1) { throw 'neural reranker model manifest schema_version must be 1' }
    if ($null -eq $manifest.model -or $manifest.model.id -cne $modelId -or
        $manifest.model.revision -cne $modelRevision -or $manifest.model.format -cne 'onnx-fp32-o2') {
        throw 'neural reranker model manifest identity does not match the pinned export'
    }
    if ($null -eq $manifest.tokenizer -or $manifest.tokenizer.class -cne 'BertJapaneseTokenizer' -or
        $manifest.tokenizer.word_tokenizer_type -cne 'basic' -or
        $manifest.tokenizer.subword_tokenizer_type -cne 'character' -or
        $manifest.tokenizer.do_lower_case -ne $false) {
        throw 'neural reranker model manifest tokenizer identity is incomplete or unexpected'
    }
    if ($null -eq $manifest.runtime -or $manifest.runtime.name -cne 'onnxruntime' -or
        $manifest.runtime.version -cne $ortVersion) {
        throw 'neural reranker model manifest ONNX Runtime identity does not match the pinned release'
    }

    $modelRecordsByPath = @{}
    foreach ($record in @($manifest.files)) {
        if ($null -eq $record -or [string]::IsNullOrWhiteSpace([string]$record.path) -or
            [string]::IsNullOrWhiteSpace([string]$record.sha256)) {
            throw 'neural reranker model manifest contains an incomplete file record'
        }
        if ($modelRecordsByPath.ContainsKey($record.path)) {
            throw "neural reranker model manifest contains duplicate file record: $($record.path)"
        }
        $modelRecordsByPath[$record.path] = $record
    }
    foreach ($relative in @('model.onnx', 'vocab.txt')) {
        if (-not $modelRecordsByPath.ContainsKey($relative)) {
            throw "neural reranker model manifest is missing required record: $relative"
        }
        $record = $modelRecordsByPath[$relative]
        $path = Join-Path ([IO.Path]::GetDirectoryName($manifestPath)) $relative
        $item = Require-File $path "neural reranker model payload $relative"
        if ([long]$record.bytes -ne $item.Length) {
            throw "neural reranker model payload size does not match manifest: $relative"
        }
        if ($record.sha256 -cne (Get-Sha256 $path)) {
            throw "neural reranker model payload SHA-256 does not match manifest: $relative"
        }
    }

    $orderedRecords = Get-NeuralPayloadRecords $PayloadDirectory
    $installerManifestPath = Join-Path $PayloadDirectory "neural\$modelDirectoryName\manifest.iss"
    Require-File $installerManifestPath 'generated installer neural manifest' | Out-Null
    $expectedInstallerManifest = Get-InstallerManifestText @($orderedRecords)
    $actualInstallerManifest = [IO.File]::ReadAllText($installerManifestPath, [Text.UTF8Encoding]::new($false))
    if ($actualInstallerManifest -cne $expectedInstallerManifest) {
        throw 'generated installer neural manifest does not exactly match the JSON manifest'
    }

    return $manifest
}

function Get-NeuralPayloadRecords([string]$PayloadDirectory) {
    $records = foreach ($relative in $neuralPayloadFiles) {
        $path = Join-Path $PayloadDirectory $relative.Replace('/', '\')
        $item = Require-File $path "neural reranker payload $relative"
        [ordered]@{
            path = $relative
            bytes = $item.Length
            sha256 = Get-Sha256 $path
        }
    }
    return @($records)
}

if ($ValidateOnly) {
    Test-NeuralPayload $OutputDirectory | Out-Null
    Write-Host "neural reranker payload validated: $OutputDirectory"
    return
}

[IO.Directory]::CreateDirectory($OutputDirectory) | Out-Null
[IO.Directory]::CreateDirectory($WorkDirectory) | Out-Null

$ortArchive = Join-Path $WorkDirectory "onnxruntime-win-x64-$ortVersion.zip"
if (-not [IO.File]::Exists($ortArchive) -or (Get-Sha256 $ortArchive) -cne $ortArchiveHash) {
    Add-Type -AssemblyName System.Net.Http
    $client = [Net.Http.HttpClient]::new()
    try {
        $bytes = $client.GetByteArrayAsync($ortArchiveUrl).GetAwaiter().GetResult()
        [IO.File]::WriteAllBytes($ortArchive, $bytes)
    } finally {
        $client.Dispose()
    }
}
if ((Get-Sha256 $ortArchive) -cne $ortArchiveHash) {
    throw 'downloaded ONNX Runtime archive does not match the pinned SHA-256'
}

$ortParent = Join-Path $WorkDirectory 'onnxruntime'
$ortRoot = Join-Path $ortParent "onnxruntime-win-x64-$ortVersion"
if (-not [IO.File]::Exists((Join-Path $ortRoot "lib\$runtimeDllName"))) {
    [IO.Directory]::CreateDirectory($ortParent) | Out-Null
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    [IO.Compression.ZipFile]::ExtractToDirectory($ortArchive, $ortParent)
}

$workerBinary = Join-Path $repository $workerRelativePath.Replace('/', '\')
$runtimeSource = Join-Path $ortRoot "lib\$runtimeDllName"
Push-Location $repository
try {
    & cargo build --release -p $workerPackage
    if ($LASTEXITCODE -ne 0) { throw "Rust neural worker release build failed for package $workerPackage" }
    Require-File $workerBinary 'built Rust neural worker' | Out-Null

    & cargo test -p $workerPackage
    if ($LASTEXITCODE -ne 0) { throw "Rust neural worker tests failed for package $workerPackage" }

    # The worker dynamically resolves ONNX Runtime beside its release binary.
    # Put the already hash-verified DLL there before the bounded self-test, then
    # copy the same bytes into the installer payload below.
    [IO.File]::Copy((Require-File $runtimeSource 'ONNX Runtime DLL').FullName,
        (Join-Path ([IO.Path]::GetDirectoryName($workerBinary)) $runtimeDllName), $true)
    Push-Location ([IO.Path]::GetDirectoryName($workerBinary))
    try {
        & $workerBinary --self-test
        if ($LASTEXITCODE -ne 0) { throw 'Rust neural worker self-test failed' }
    }
    finally {
        Pop-Location
    }
}
finally {
    Pop-Location
}

if ([string]::IsNullOrWhiteSpace($PreExportedModelDirectory)) {
    $uv = Join-Path $env:USERPROFILE '.local\bin\uv.exe'
    if (-not [IO.File]::Exists($uv)) { throw "uv is missing: $uv" }
    $venv = Join-Path $WorkDirectory '.venv'
    if (-not [IO.File]::Exists((Join-Path $venv 'Scripts\python.exe'))) {
        & $uv venv --python 3.11 $venv
        if ($LASTEXITCODE -ne 0) { throw 'could not create the task-specific Python environment' }
    }
    & $uv pip install --python (Join-Path $venv 'Scripts\python.exe') `
        'torch==2.13.0' 'transformers==4.57.6' 'optimum==2.1.0' `
        'optimum-onnx==0.1.0' 'onnx==1.22.0' 'onnxruntime==1.28.0'
    if ($LASTEXITCODE -ne 0) { throw 'could not install pinned model-export packages' }
    $exportRoot = Join-Path $WorkDirectory ("export-" + [Guid]::NewGuid().ToString('N'))
    $modelSource = Join-Path $exportRoot 'source'
    $modelOutput = Join-Path $exportRoot 'onnx'
    & (Join-Path $venv 'Scripts\python.exe') (Join-Path $repository 'scripts\export-neural-model.py') `
        --source-directory $modelSource --output-directory $modelOutput
    if ($LASTEXITCODE -ne 0) { throw 'pinned neural model export failed' }
} else {
    $modelOutput = [IO.Path]::GetFullPath($PreExportedModelDirectory)
}

foreach ($required in @('model.onnx', 'vocab.txt', 'manifest.json')) {
    Require-File (Join-Path $modelOutput $required) "pre-exported model $required" | Out-Null
}

$modelDestination = Join-Path $OutputDirectory "neural\$modelDirectoryName"
$licenseDestination = Join-Path $OutputDirectory 'licenses'
[IO.Directory]::CreateDirectory($modelDestination) | Out-Null
[IO.Directory]::CreateDirectory($licenseDestination) | Out-Null
[IO.File]::Copy((Require-File $workerBinary 'built Rust neural worker').FullName, (Join-Path $OutputDirectory 'sakura_neural_worker.exe'), $true)
[IO.File]::Copy((Require-File $runtimeSource 'ONNX Runtime DLL').FullName, (Join-Path $OutputDirectory $runtimeDllName), $true)
[IO.File]::Copy((Join-Path $modelOutput 'model.onnx'), (Join-Path $modelDestination 'model.onnx'), $true)
[IO.File]::Copy((Join-Path $modelOutput 'vocab.txt'), (Join-Path $modelDestination 'vocab.txt'), $true)
[IO.File]::Copy((Join-Path $modelOutput 'manifest.json'), (Join-Path $modelDestination 'manifest.json'), $true)
[IO.File]::Copy((Require-File (Join-Path $ortRoot 'LICENSE') 'ONNX Runtime license').FullName, (Join-Path $licenseDestination 'onnxruntime-MIT.txt'), $true)
[IO.File]::Copy((Require-File (Join-Path $ortRoot 'ThirdPartyNotices.txt') 'ONNX Runtime third-party notices').FullName, (Join-Path $licenseDestination 'onnxruntime-ThirdPartyNotices.txt'), $true)
[IO.File]::Copy(
    (Require-File (Join-Path $repository 'THIRD_PARTY_LICENSES\ku-nlp-deberta-v2-tiny-japanese-char-wwm.txt') 'DeBERTa model license').FullName,
    (Join-Path $licenseDestination 'ku-nlp-deberta-v2-tiny-japanese-char-wwm.txt'),
    $true
)

$records = Get-NeuralPayloadRecords $OutputDirectory
$installerManifestPath = Join-Path $OutputDirectory "neural\$modelDirectoryName\manifest.iss"
[IO.File]::WriteAllText($installerManifestPath, (Get-InstallerManifestText @($records)), [Text.UTF8Encoding]::new($false))
Test-NeuralPayload $OutputDirectory | Out-Null
Write-Host "Neural reranker artifacts: $OutputDirectory"
